backend:
  name: github
  branch: stg
  repo: dgladmananshincare-png/test-anshin-docs
  base_url: https://stg-test-anshin-docs.vercel.app/
  auth_endpoint: /auth

publish_mode: editorial_workflow

# These lines should *not* be indented
media_folder: "static/img" # Media files will be stored in the repo under static/images/uploads
public_folder: "/img/" # The src attribute for uploaded media will begin with /images/uploads

display_url: https://stg-test-anshin-docs.vercel.app/
locale: "ja"

search: false

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

collections:
- name: appStartGuide
  label: "app/start-guide"
  folder: docs/app/start-guide
  identifier_field: title
  extension: md
  create: true
  slug: "{{id}}"
  fields:
    - { name: id, label: Id, widget: string } 
    - { name: title, label: Title, widget: string } 
    - { name: subtitle, label: Subtitle, widget: string, required: false}
    - { name: sidebar_position, label: Sidebar Position, widget: number }
    - name: metadata
      label: Metadata
      widget: object
      fields:
        - { name: pageId, label: Page ID, widget: string }
        - { name: categoryId, label: Category ID, widget: string }
        - { name: guideId, label: Guide ID, widget: string }
    - { name: body, label: Body, widget: markdown }

- name: appPublic
  label: "app/public"
  folder: docs/app/public
  identifier_field: title
  extension: md
  create: true
  slug: "{{id}}"
  fields:
    - { name: id, label: Id, widget: string } 
    - { name: title, label: Title, widget: string } 
    - { name: subtitle, label: Subtitle, widget: string, required: false}
    - { name: sidebar_position, label: Sidebar Position, widget: number }
    - name: metadata
      label: Metadata
      widget: object
      fields:
        - { name: pageId, label: Page ID, widget: string }
        - { name: categoryId, label: Category ID, widget: string }
        - { name: guideId, label: Guide ID, widget: string }
    - { name: body, label: Body, widget: markdown }