backend:
  name: github
  branch: stg
  repo: dgladmananshincare-png/test-anshin-docs
  base_url: https://stg-test-anshin-docs.vercel.app/
  auth_endpoint: /auth
publish_mode: editorial_workflow
media_folder: static/img
public_folder: /img/
display_url: https://stg-test-anshin-docs.vercel.app/
locale: ja
search: false
slug:
  encoding: ascii
  clean_accents: true
  sanitize_replacement: _
collections:
  - name: app
    label: app
    folder: docs/app
    identifier_field: title
    extension: md
    create: true
    slug: "{{id}}"
    fields: &a1
      - name: id
        label: Id
        widget: string
      - name: title
        label: Title
        widget: string
      - name: subtitle
        label: Subtitle
        widget: string
        required: false
      - name: sidebar_position
        label: Sidebar Position
        widget: number
      - name: metadata
        label: Metadata
        widget: object
        fields:
          - name: pageId
            label: Page ID
            widget: string
          - name: categoryId
            label: Category ID
            widget: string
          - name: guideId
            label: Guide ID
            widget: string
      - name: body
        label: Body
        widget: markdown
  - name: app_aggregate
    label: app/aggregate
    folder: docs/app/aggregate
    identifier_field: title
    extension: md
    create: true
    slug: "{{id}}"
    fields: *a1
  - name: app_attendance
    label: app/attendance
    folder: docs/app/attendance
    identifier_field: title
    extension: md
    create: true
    slug: "{{id}}"
    fields: *a1
  - name: app_billing
    label: app/billing
    folder: docs/app/billing
    identifier_field: title
    extension: md
    create: true
    slug: "{{id}}"
    fields: *a1
  - name: app_contract
    label: app/contract
    folder: docs/app/contract
    identifier_field: title
    extension: md
    create: true
    slug: "{{id}}"
    fields: *a1
  - name: app_helper
    label: app/helper
    folder: docs/app/helper
    identifier_field: title
    extension: md
    create: true
    slug: "{{id}}"
    fields: *a1
  - name: app_product
    label: app/product
    folder: docs/app/product
    identifier_field: title
    extension: md
    create: true
    slug: "{{id}}"
    fields: *a1
  - name: app_public
    label: app/public
    folder: docs/app/public
    identifier_field: title
    extension: md
    create: true
    slug: "{{id}}"
    fields: *a1
  - name: app_salary
    label: app/salary
    folder: docs/app/salary
    identifier_field: title
    extension: md
    create: true
    slug: "{{id}}"
    fields: *a1
  - name: app_start_guide
    label: app/start-guide
    folder: docs/app/start-guide
    identifier_field: title
    extension: md
    create: true
    slug: "{{id}}"
    fields: *a1
