# This is a dummy config.yml file.
backend:
  name: dummy
media_folder: "static/img/guide"
media_library:
  name: "" # minimal dummy value
collections:
  - name: dummy
    label: Dummy
    files:
      - file: "dummy.md"
        label: "Dummy File"
        name: "dummy"
        fields:
          - { label: "Title", name: "title", widget: "string" }